[package]
name = "ebpf_test"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = { version = "0.1.1", default-features = false }

[profile.release]
opt-level = "z"
lto = false
panic = "abort"
strip = "debuginfo"
codegen-units = 1
