[package]
name = "ssh_session_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = { version = "0.1.1" }

[profile.release]
opt-level = "z"
lto = false
panic = "abort"
strip = "debuginfo"
codegen-units = 1
